// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDI3ykWv0R0UZWVejeaeZVT2RZnnAeJas',
    appId: '1:808317363646:web:91e267211e5431e53645ef',
    messagingSenderId: '808317363646',
    projectId: 'shoppercart-f107f',
    authDomain: 'shoppercart-f107f.firebaseapp.com',
    storageBucket: 'shoppercart-f107f.appspot.com',
    measurementId: 'G-P2GYYK69EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmn9DtP-aqiIVbN3GvfcDwxIb_Hzuq-as',
    appId: '1:87858658185:android:5c859a02f00d7369e17f58',
    messagingSenderId: '87858658185',
    projectId: 'flutter-fire-cli-3f0c7',
    storageBucket: 'flutter-fire-cli-3f0c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkSm4hRj8Ud6GKmT_C4bpmNhSicUhDjdg',
    appId: '1:87858658185:ios:5da9c036d750cfc6e17f58',
    messagingSenderId: '87858658185',
    projectId: 'flutter-fire-cli-3f0c7',
    storageBucket: 'flutter-fire-cli-3f0c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterFireCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOmQAtxyC4eZhF9q4c6a2sXUtyISh_lr8',
    appId: '1:808317363646:ios:9b5241a409160f043645ef',
    messagingSenderId: '808317363646',
    projectId: 'shoppercart-f107f',
    storageBucket: 'shoppercart-f107f.appspot.com',
    iosBundleId: 'com.example.firebase131Flutterfire.RunnerTests',
  );
}